build:
    nodes:
        php-scrutinizer-run:
            project_setup:
                override: true
            tests:
                override:
                    - echo 'No need to run tests'
    dependencies:
        override:
            -
                command: 'echo "No need to install dependencies"'
    environment:
        php:
            version: 7.4.20
    tests:
        override: true
    project_setup:
        override: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
