<?php declare(strict_types=1);
/**
 * PHP version 7.4
 *
 * This source file is subject to the license that is bundled with this package in the file LICENSE.
 */

namespace PhUml\Generators;

use PhUml\Code\Codebase;
use PhUml\Processors\GraphvizProcessor;
use PhUml\Processors\OutputContent;

/**
 * It generates a file with a digraph in DOT format that can be used to create a class diagram
 *
 * You might want to create a different output using either `neato` or `dot`.
 * The file this command creates can be used as an intermediate step.
 * For instance:
 *
 * `neato -Tpdf output.gv > output.pdf`
 *
 * Where `output.gv` is the file generated by this action
 */
final class DigraphGenerator
{
    protected GraphvizProcessor $digraphProcessor;

    public function __construct(GraphvizProcessor $digraphProcessor)
    {
        $this->digraphProcessor = $digraphProcessor;
    }

    public function generateDigraph(Codebase $codebase, ProgressDisplay $display): OutputContent
    {
        $display->runningProcessor($this->digraphProcessor);
        return $this->digraphProcessor->process($codebase);
    }
}
